apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "memory-chart.fullname" . }}
  labels:
    {{- include "memory-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "memory-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "memory-chart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with include "memory-chart.imagePullSecrets" . | fromYamlArray }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "memory-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ include "memory-chart.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: VITE_IDENTITY_PROVIDER
              value: {{ .Values.environment.VITE_IDENTITY_PROVIDER | quote }}
            - name: VITE_SSO_SERVER_URL
              value: {{ .Values.environment.VITE_SSO_SERVER_URL | quote }}
            - name: VITE_OAUTH_CLIENT_ID
              value: {{ .Values.environment.VITE_OAUTH_CLIENT_ID | quote }}
            - name: VITE_OAUTH_REALM
              value: {{ .Values.environment.VITE_OAUTH_REALM | quote }}
            - name: VITE_API_URL
              value: {{ .Values.environment.VITE_API_URL | quote }}
            - name: VITE_OLLAMA_API_URL
              value: {{ .Values.environment.VITE_OLLAMA_API_URL | quote }}
            - name: VITE_AVAILABLE_MODELS
              value: {{ .Values.environment.VITE_AVAILABLE_MODELS | toJson | replace "\"" "\\\"" | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
