{{- /*
Copyright Martin Cote, Inc. All Rights Reserved.
*/}}

{{- if .Values.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "memory-chart.fullname" . }}-pdb
  namespace: "default"
  labels:
    {{ include "memory-chart.labels" . | nindent 4 }}
    app: {{ include "memory-chart.fullname" . }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if or .Values.pdb.maxUnavailable (not .Values.pdb.minAvailable)}}
  maxUnavailable: {{ .Values.pdb.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
        app: {{ include "memory-chart.fullname" . }}
{{- end }}